/**
 * Post API
 *
 * Documentation of Post API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.posts.models

import com.talky.mobile.api.posts.models.UserDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Uniq identifier of the post
 * @param author 
 * @param createdAt Post creation date
 * @param content Post text content
 * @param privacy Post privacy (public / private)
 * @param assets List of assets links, these are temporary link, only available during a certain period of time.
 */

data class PostDto (

    /* Uniq identifier of the post */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "author")
    val author: UserDto? = null,

    /* Post creation date */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Post text content */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Post privacy (public / private) */
    @Json(name = "privacy")
    val privacy: PostDto.Privacy? = null,

    /* List of assets links, these are temporary link, only available during a certain period of time. */
    @Json(name = "assets")
    val assets: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * Post privacy (public / private)
     *
     * Values: pUBLIC,pRIVATE
     */
    enum class Privacy(val value: kotlin.String) {
        @Json(name = "PUBLIC") pUBLIC("PUBLIC"),
        @Json(name = "PRIVATE") pRIVATE("PRIVATE");
    }
}

