/**
 * Users API
 *
 * Documentation of Users API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.users.models

import com.talky.mobile.api.users.models.PageableObject
import com.talky.mobile.api.users.models.Sort
import com.talky.mobile.api.users.models.UserDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param totalPages 
 * @param totalElements 
 * @param propertySize 
 * @param content 
 * @param number 
 * @param sort 
 * @param pageable 
 * @param numberOfElements 
 * @param first 
 * @param last 
 * @param empty 
 */

data class PageUserDto (

    @Json(name = "totalPages")
    val totalPages: kotlin.Int? = null,

    @Json(name = "totalElements")
    val totalElements: kotlin.Long? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "content")
    val content: kotlin.collections.List<UserDto>? = null,

    @Json(name = "number")
    val number: kotlin.Int? = null,

    @Json(name = "sort")
    val sort: Sort? = null,

    @Json(name = "pageable")
    val pageable: PageableObject? = null,

    @Json(name = "numberOfElements")
    val numberOfElements: kotlin.Int? = null,

    @Json(name = "first")
    val first: kotlin.Boolean? = null,

    @Json(name = "last")
    val last: kotlin.Boolean? = null,

    @Json(name = "empty")
    val empty: kotlin.Boolean? = null

)

