/**
 * Users API
 *
 * Documentation of Users API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.users.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param empty 
 * @param unsorted 
 * @param sorted 
 */

data class Sort (

    @Json(name = "empty")
    val empty: kotlin.Boolean? = null,

    @Json(name = "unsorted")
    val unsorted: kotlin.Boolean? = null,

    @Json(name = "sorted")
    val sorted: kotlin.Boolean? = null

)

