/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.social.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param recipient UUID of the user that will recieve the friend request
 */

data class CreateFriendRequestRequestDto (

    /* UUID of the user that will recieve the friend request */
    @Json(name = "recipient")
    val recipient: java.util.UUID? = null

)

