/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.social.models

import com.talky.mobile.api.social.models.UserDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id UUID of the friendship
 * @param sender 
 * @param recipient 
 * @param status Current status of the friend request
 * @param creationDate Creation datetime
 * @param lastUpdate Last update datetime
 */

data class FriendRequestDto (

    /* UUID of the friendship */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "sender")
    val sender: UserDto? = null,

    @Json(name = "recipient")
    val recipient: UserDto? = null,

    /* Current status of the friend request */
    @Json(name = "status")
    val status: FriendRequestDto.Status? = null,

    /* Creation datetime */
    @Json(name = "creationDate")
    val creationDate: java.time.OffsetDateTime? = null,

    /* Last update datetime */
    @Json(name = "lastUpdate")
    val lastUpdate: java.time.OffsetDateTime? = null

) {

    /**
     * Current status of the friend request
     *
     * Values: aCCEPTED,pENDING,dENIED
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "ACCEPTED") aCCEPTED("ACCEPTED"),
        @Json(name = "PENDING") pENDING("PENDING"),
        @Json(name = "DENIED") dENIED("DENIED");
    }
}

