/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.social.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Uniq UUID of the User
 * @param displayedName Name that the use chose to display
 * @param profilePicture Link to the user profile picture
 * @param lastSeen Date time of when the user was last online
 * @param friendshipId UUID of the friendship between the current user and this user
 */

data class FriendDto (

    /* Uniq UUID of the User */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    /* Name that the use chose to display */
    @Json(name = "displayedName")
    val displayedName: kotlin.String? = null,

    /* Link to the user profile picture */
    @Json(name = "profilePicture")
    val profilePicture: kotlin.String? = null,

    /* Date time of when the user was last online */
    @Json(name = "lastSeen")
    val lastSeen: java.time.OffsetDateTime? = null,

    /* UUID of the friendship between the current user and this user */
    @Json(name = "friendshipId")
    val friendshipId: java.util.UUID? = null

)

