/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.social.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Uniq UUID of the message
 * @param friendshipId UUID of the friendship where the message was sended
 * @param author UUID of the user that made the request
 * @param content Text content of the message
 * @param createdAt Creation date of the message
 */

data class MessageDto (

    /* Uniq UUID of the message */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    /* UUID of the friendship where the message was sended */
    @Json(name = "friendshipId")
    val friendshipId: java.util.UUID? = null,

    /* UUID of the user that made the request */
    @Json(name = "author")
    val author: java.util.UUID? = null,

    /* Text content of the message */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Creation date of the message */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

