/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.social.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param status New status of the request (ACCEPTED / DENIED / PENDING)
 */

data class UpdateFriendRequestRequestDto (

    /* New status of the request (ACCEPTED / DENIED / PENDING) */
    @Json(name = "status")
    val status: UpdateFriendRequestRequestDto.Status? = null

) {

    /**
     * New status of the request (ACCEPTED / DENIED / PENDING)
     *
     * Values: aCCEPTED,pENDING,dENIED
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "ACCEPTED") aCCEPTED("ACCEPTED"),
        @Json(name = "PENDING") pENDING("PENDING"),
        @Json(name = "DENIED") dENIED("DENIED");
    }
}

