/**
 * Users API
 *
 * Documentation of Users API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url Temporary Url of an asset. Warning : The Asset miht not exist.
 */

data class AssetTemporaryLinkResponseDto (

    /* Temporary Url of an asset. Warning : The Asset miht not exist. */
    @SerializedName("url")
    val url: kotlin.String? = null

)

