/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empty 
 * @param unsorted 
 * @param sorted 
 */

data class Sort (

    @SerializedName("empty")
    val empty: kotlin.Boolean? = null,

    @SerializedName("unsorted")
    val unsorted: kotlin.Boolean? = null,

    @SerializedName("sorted")
    val sorted: kotlin.Boolean? = null

)

