/**
 * Social API
 *
 * Documentation of Social API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.talky.mobile.api.models


import com.google.gson.annotations.SerializedName

/**
 * Details of the user that recieved the friend request
 *
 * @param id Uniq UUID of the User
 * @param displayedName Name that the use chose to display
 * @param profilePicture Link to the user profile picture
 * @param lastSeen Date time of when the user was last online
 */

data class UserDto (

    /* Uniq UUID of the User */
    @SerializedName("id")
    val id: java.util.UUID? = null,

    /* Name that the use chose to display */
    @SerializedName("displayedName")
    val displayedName: kotlin.String? = null,

    /* Link to the user profile picture */
    @SerializedName("profilePicture")
    val profilePicture: kotlin.String? = null,

    /* Date time of when the user was last online */
    @SerializedName("lastSeen")
    val lastSeen: java.time.OffsetDateTime? = null

)

